// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/_locales/en/messages.json"
    | "/_locales/ko/messages.json"
    | "/image/icon-128.png"
    | "/image/icon-16.png"
    | "/image/icon-24.png"
    | "/image/icon-256.png"
    | "/image/icon-32.png"
    | "/image/icon-64.png"
    | "/image/icon.png"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
